### ISSUE TITLE
fastqc fails with Value Error

### ISSUE THREAD

**Issue by zdk123** [nf-core/bacass#10]
Hi all. I'm excited to get started with your workflow. However, I cannot as of yet run the fastqc step, at least on nextflow version 19.07.0.5106 / docker.

Here's a snipped of the output:
```
fastqc -t {task.cpus} -q 1_R1_001_trm-cmb.R1.fastq.gz 1_R1_001_trm-cmb.R2.fastq.gz
...
Value "{task.cpus}" invalid for option threads (number expected)
```

Looks like the actual value of task.cpus is not getting substituted. Perhaps there is a typo in [Line 252 of main.tf](https://github.com/nf-core/bacass/blob/master/main.nf#L252):
Proposed change is:
```diff
-     fastqc -t {task.cpus} -q ${fq1} ${fq2}
+    fastqc -t ${task.cpus} -q ${fq1} ${fq2}
``` 

I can issue a PR, but this seems like a straightforward fix.
thanks!

**Comment by apeltzer** [comment]
Can you use the dev branch ? That should be fixed there and I’ll update the nanopore branch soon

**Comment by apeltzer** [comment]
The `nanopore` branch contains a fix and can be used for short read data too - let me know if that helps 👍

**Comment by zdk123** [comment]
thanks I can switch to the branch.

**Comment by apeltzer** [comment]
Okay please reopen if the problem persists there 👍
