### ISSUE TITLE
Improvements in  forked repository: KmerFinder, Estimation of Reference Genome,  Custom Quast, and Custom MultiQC Reports

### ISSUE THREAD

**Issue by Daniel-VM** [nf-core/bacass#109]
## Overview

Hello!, My colleagues and I have been actively working on enhancing the nf-core/bacass workflow to address lab-specific challenges in bacterial genome assembly. We are happy to add  these improvements into the main nf-core/bacass repository in case you are interested.

Currently, these enhancements have been implemented in my [local fork of nf-core/bacass on the buisciii-develop branch](https://github.com/Daniel-VM/bacass/tree/buisciii-develop).
```
nextflow run main.nf \
        -profile singularity,test \
        --skip_kmerfinder false \
        --kmerfinderdb path/to/kmerfinder_db/bacteria \
        --ncbi_assembly_metadata path/to/ncbi_assembly_metadata/assembly_summary_bacteria.txt \
        --outdir ./results \
        -w ./work \
        -resume
```
### 1. Kmerfinder Subworkflow:

- Added a local KmerFinder module for read quality control (QC) and purity assessment.
- Developed a local module to compile KmerFinder results from all samples into a comprehensive CSV summary file.
- Implemented a method to group input samples (*.fastq, *.fasta, and other files...) based on the reference genome estimated with KmerFinder.
- Created a local module to identify the reference genome estimated with KmerFinder in the NCBI database and download this genome. This reference genome is then utilized to retrieve relevant metrics from QUAST, such as the percentage of genome fraction. This functionality is particularly valuable when input samples belong to different species, requiring more than one reference for a comprehensive by_reference_genome report.

### 2. Quast Assembly QC by Grouping Samples:

- Modified Quast execution when KmerFinder is invoked. Now, Quast runs twice:
- Initial 'general' Quast without reference genome files (*.fna, *.gff).
- Subsequent 'by reference genome' Quast, providing a Quast reports that agregates samples and their reference genome (estimated with kmerfinder).

### 3. Custom MultiQC Reports:

- Incorporated a custom MultiQC module into the workflow.
- Added multiqc_config.yml files for short, long and hybrid assembly modes (they work when kmerfinder is invoked, otherwise standard multiqc report is generated). 
- Upon invoking KmerFinder, a custom MultiQC HTML report is generated using the MULTIQC() module. This report consolidates metrics from KmerFinder, Quast, and other relevant sources, presenting them together in an overview table located in the first section of the report. See image: 

![Screenshot from 2024-01-04 16-23-26](https://github.com/nf-core/bacass/assets/69470278/03904b68-1d52-4277-b208-c99611136464)

## Foot note

If you think these improvements could be implemented in nf-core/bacass, let me know so I can work on the test data and test profile.

**Comment by d4straub** [comment]
Looks actually very interesting to me. But I do not have experience with those tools and did not run the branch. I trust your judgment for now that this indeed is good practice.

I browsed over it and there were some minor points, e.g. a param with skip_* (such as `skip_kmerfinder`) shouldnt be by default `true` I think. I am not very much into MultiQC, so I am not sure why a custom module is needed, I thought MultiQC can be configured to do almost anything, but you have your reasons I assume.

So yes, I think that would be nice to add into the nf-core repo.
