### ISSUE TITLE
prokka doesn't work in docker nfcore/bacass:1.0.0 

### ISSUE THREAD

**Issue by samlhao** [nf-core/bacass#11]
It seems that the default docker image doesn't have a functional prokka installation due to expiry of tbl2asn. At the moment, I've gotten around this by specifying a different docker image for the prokka process, but it would be nice if this wasn't necessary.

**Comment by apeltzer** [comment]
Yeah, the problem we have with this is that this will always run out after a while - the only thing we can do is either skip prokka and/or use the latest release with newer prokka and thus tbl2asn method. I'm short before releasing 1.1.0 that will be able to work again.

**Comment by apeltzer** [comment]
We can't / won't break the former Docker container for reproducibility reasons. I agree that this isN't optimal and also filed complaints at the prokka repository (see here: https://github.com/tseemann/prokka/issues/444 ) - we also added support for an alternative annotation method called DFAST as mentioned in the issue #12 , so you can have a go with that upon release of 1.1.0 which is now imminent :-)
