### ISSUE TITLE
Replace Prokka with Dfast

### ISSUE THREAD

**Issue by marchoeppner** [nf-core/bacass#12]
In reference to #11 - would it be an option to simply replace Prokka with Dfast:
https://github.com/nigyta/dfast_core

From my tests, it seems to outperform Prokka in terms of "loci annotated/named" - and it's also on bioconda and easily as fast as Prokka. 

The issue with Prokka and Tbl2asn seems like it won't be fixable - and having the Docker image "expire" every so often is probably not an ideal solution moving forward. 

Cheers,
Marc

**Comment by apeltzer** [comment]
Hi Marc!

I submitted an issue in the Prokka repository to check whether replacing tbl2asn is a feasible option. I can make the annotation tool feature both tools in the pipeline for starters so that users have a choice of which one they want to use for example.

**Comment by marchoeppner** [comment]
Thanks for looking into it! I think Prokka has been struggling with this for some time, there are several issues on this on github. 

For Dfast, you will have to make a second container - won't play nice with Unicycler.

**Comment by apeltzer** [comment]
Oh my, how i love these incompatible packaging things... not your fault but I see these too often recently ;-) 

Yes, Prokka has that since a while but I think Torsten Seeman will take care of it at some point. If Prokka weren't Perl, I'd even have a go myself ;-)

**Comment by apeltzer** [comment]
Added in #13
