### ISSUE TITLE
Running error of exit status 255

### ISSUE THREAD

**Issue by aslangabriel99** [nf-core/bacass#129]
### Description of the bug

I ran the pipeline with my own data the command line is "nextflow run nf-core/bacass -r 2.2.0 -profile docker --input ./minikrakendb/baccsamplesheet.tsv --kraken2db /home/aslangabriel/minikrakendb/k2_standard_08gb_20240112.tar.gz --max_cpus 12 --max_memory '125.GB' --outdir ./minikrakendb/results", my sample sheet looks like that
![image](https://github.com/nf-core/bacass/assets/56073902/d5f4ae52-e7c6-42a5-8dba-b521ff05cd84)
and the error message was as follows
"-[nf-core/bacass] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_BACASS:BACASS:FASTQ_TRIM_FASTP_FASTQC:FASTP (JSAHVC01)'

Caused by:
  Process `NFCORE_BACASS:BACASS:FASTQ_TRIM_FASTP_FASTQC:FASTP (JSAHVC01)` terminated with an error exit status (255)

Command executed:

  [ ! -f  JSAHVC01_1.fastq.gz ] && ln -sf JSAHVC01_S1_R1.fastq.gz JSAHVC01_1.fastq.gz
  [ ! -f  JSAHVC01_2.fastq.gz ] && ln -sf JSAHVC01_S1_R2.fastq.gz JSAHVC01_2.fastq.gz
  fastp \
      --in1 JSAHVC01_1.fastq.gz \
      --in2 JSAHVC01_2.fastq.gz \
      --out1 JSAHVC01_1.fastp.fastq.gz \
      --out2 JSAHVC01_2.fastp.fastq.gz \
      --json JSAHVC01.fastp.json \
      --html JSAHVC01.fastp.html \
       \
       \
       \
      --thread 8 \
      --detect_adapter_for_pe \
       \
      2> >(tee JSAHVC01.fastp.log >&2)
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_BACASS:BACASS:FASTQ_TRIM_FASTP_FASTQC:FASTP":
      fastp: $(fastp --version 2>&1 | sed -e "s/fastp //g")
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  ERROR: Failed to open file: JSAHVC01_1.fastq.gz

Work dir:
  /home/aslangabriel/work/d0/6d8835e9fba25be3a34dcf33080fa2

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

",  I have changed the file name per se the test example. please help me to fix it.

**Comment by Daniel-VM** [comment]
Hi @aslangabriel99 !,

Command error says that is something related to the file/filepath. Let's try to debug it.

- Double check filepath
- try `gunzip -t /home/shpc_1100038APECrawread/JSAHVC01_S1_R1.fastq.gz` to verify file integrity. 
- Does the work/d0/6d8835e9fba25be3a34dcf33080fa2/.command.* files provide any clue?.
