### ISSUE TITLE
kraken2 failing in docker on ubuntu

### ISSUE THREAD

**Issue by zdk123** [nf-core/bacass#16]
The example run fails on my Ubuntu machine
```sh
nextflow run nf-core/bacass -r 1.1.0 -profile docker --input https://raw.githubusercontent.com/nf-core/test-datasets/bacass/bacass_short.csv --kraken2db ${PWD}/minikraken2 --max_memory 40.GB --max_cpus 10
```

with
```
Command exit status:
  2

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  kraken2: database ("../minikraken2") does not contain necessary file taxo.k2d
```

However, I can use minikraken2 db locally. Docker version 19.03.5, nextflow version is 19.10.0.5170. I'm only seeing this in Ubuntu 18.04: the test runs fine on my macbook.

Any guidance?

**Comment by apeltzer** [comment]
Is the file specified by the call (`taxo.k2d`) present? Not sure what this is... can also run locally with my kraken2db just fine (and already used this for 2 projects...). Should probably investigate a bit further then what causes this...

**Comment by zdk123** [comment]
Could it be a volume mounting issue?

For example, I launched the bacass container with the working directory mounted as a volume and run using a local profile and I don't have any issues running kraken2 (e.g. the necessary files are definitely present):
E.g (no errors here):
```sh
## host
docker run --entrypoint /bin/bash -m 40GB -v $PWD:$PWD -w $PWD -ti nfcore/bacass:1.1.0

## container
conda install -c bioconda nextflow
nextflow run nf-core/bacass -r 1.1.0 --input https://raw.githubusercontent.com/nf-core/test-datasets/bacass/bacass_short.csv --kraken2db ${PWD}/minikraken2 --max_memory 40.GB --max_cpus 10
```

**Comment by apeltzer** [comment]
Ok this seems to be more of a Docker issue than a pipeline problem - closing for now. If there is something similar coming up too frequently, let me know.
