### ISSUE TITLE
tbl2asn is expired

### ISSUE THREAD

**Issue by zdk123** [nf-core/bacass#17]
This breaks prokka. The docker container / conda environment needs to be rebuilt
see: https://github.com/tseemann/prokka/issues/453

**Comment by apeltzer** [comment]
Which container? 

I already tried actively pursuing the author of prokka here https://github.com/tseemann/prokka/issues/444 but there is not really a solution. For the sake of reproducibility, its also not really an option to "redo" the container every 6months. The alternative annotation tool shipped with 1.1.0 of the pipeline should however be usable nevertheless ...? 

Sorry, this is more of an upstream issue & there is not really a fix until this was fixed either in tbl2asn or prokka drops usage of  this method/tool....

**Comment by zdk123** [comment]
I am using nfcore/bacass:1.1.0. I see that this is an ongoing issue for prokka/tbl2asn users, thanks for pointing that out.

In another container we're building ourselves, grabbing the newer binary from the ftp site worked well enough. I'll try dfast too and see if those results are acceptable, thanks!

**Comment by apeltzer** [comment]
Yes, sorry that there isn't a "proper" solution as of now - the other thread in Prokka also links to bioconda where people were discussing potential solutions to resolve that problem. Can't really "fix" it in here 👎

**Comment by angelovangel** [comment]
Dear @apeltzer,
I agree that it is critical to maintain reproducibility, and redoing the container every 6 months is not a solution. On the other hand, `-profile test,docker` automatically failing because of this issue is also not an option, right? Currently it fails, I will make a PR to include a `test_dfast` profile (using dfast instead of prokka) for the time being,  you cold consider making this the default `test` profile in the future in case the issue is not resolved otherwise.

Best,
Angel

**Comment by vinisalazar** [comment]
Hi,

is this issue still ongoing? I remember having a similar problem with Prokka in the past and now my bacass workflow has failed in the Prokka step.

Here's my traceback:
Could not run command: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.14.5 from https://github.com/tseemann/prokka' -Z JAMM0388_annotation\/JAMM0388\.err -i JAMM0388_annotation\/JAMM0388\.fsa 2> /dev/null

Can I assume this comes from the tbl2asn version problem described by @zdk123 ?

Thank you for any assistance you can provide,
V

**Comment by apeltzer** [comment]
A version of tbl2asn without timeout is coming soon 🎉  - once we have that upstream available, I'll make a re-release of the pipleine to make things 100% reproducible (even after  6 months!) :-)

**Comment by angelovangel** [comment]
That’s great, it was a never-ending headache for many.

**Comment by apeltzer** [comment]
That one could also help: https://github.com/bioconda/bioconda-recipes/pull/20073

**Comment by zdk123** [comment]
will test this today, thanks!

**Comment by apeltzer** [comment]
Just keep in mind that the newest version of `tbl2asn` will not have the timeout thing anymore. I guess it will just take some time to have this updated on bioconda, then these issues will go away hopefully forever ;-)

**Comment by zdk123** [comment]
We're having issues with tbl2asn-forever on nextflow. Might be related to https://github.com/audy/tbl2asn-forever/issues/2

**Comment by apeltzer** [comment]
Yeah I might just wait until tbl2asn (the original one) is updated and then give it a go 👍
