### ISSUE TITLE
Bakta running only for one sample

### ISSUE THREAD

**Issue by SchwarzMarek** [nf-core/bacass#171]
### Description of the bug

When running `bacass` for multiple samples, `bakta` output is produced only for one of them.
Execution trace and sw version are included in zip. (no `.nextflow.log` for this one, sorry)

### Relevant files

[pipeline_info.zip](https://github.com/user-attachments/files/17203426/pipeline_info.zip)

**Comment by Daniel-VM** [comment]
Hi @SchwarzMarek ,

I have ran `-r dev` and no issues... Can you try to reproduce this bug?

```console
nextflow run main.nf -profile test,docker --annotation_tool bakta --baktadb_download true --outdir results
```

![Image](https://github.com/user-attachments/assets/4dbe45db-4b87-403f-bda2-6854bc5e71b7)

**Comment by SchwarzMarek** [comment]
Hi,
still no luck...

[.nextflow.log](https://github.com/user-attachments/files/17436468/default.nextflow.log)


![Image](https://github.com/user-attachments/assets/7782748f-cb67-42cd-b190-7f4e1098ee72)

**Comment by Daniel-VM** [comment]
It seems something went wrong with the assembly step in sample ERR044595. Was the FASTA file generated correctly? There is no value under the `# contig` column for this sample.

**Comment by SchwarzMarek** [comment]
I can't see anything wrong with the assembly step. I noticed this issue when I wanted more precise annotation than those provided by prokka and did rerun with bakta. With prokka, I had annotations for every sample. One thing to note is that I was using full bakta db then (and also for this test data here).

I'm uploading the full multiqc report. [multiqc.zip](https://github.com/user-attachments/files/17503347/multiqc.zip)

Best
Marek

**Comment by Daniel-VM** [comment]
Got it! Thanks for testing it out. If possible, please review it here: https://github.com/nf-core/bacass/pull/178
