### ISSUE TITLE
Failed to create conda environment (timeout?)

### ISSUE THREAD

**Issue by xlinxlin** [nf-core/bacass#24]
When I ran the command `nextflow run nf-core/bacass --input bacass_short.csv --skip_kraken2 -profile conda` by using your test data then I got the error message:

> Caused by: 
>   Failed to create Conda environment
>   ...
>   Status: 120

According to another post here: https://github.com/nextflow-io/nextflow/issues/1081, I think it maybe also caused by time out.

Can you add this line `conda { createTimeout = '1 h' }` into your `nextflow.config` file then let me try it again? Thanks!

**Comment by apeltzer** [comment]
Conda won't work as we need multiple environments per process - quast needs a separate container, same for unicycler and some other tools (python 2 + python3 in one environment doesn't work fine :-( )

**Comment by apeltzer** [comment]
Added a disclaimer to the usage documentation to make this more clear
