### ISSUE TITLE
skip-kraken2 requires Kraken2 DB arg

### ISSUE THREAD

**Issue by ropolomx** [nf-core/bacass#26]
Running the following command using `bacass` 1.1.0:
`nextflow run nf-core/bacass --input bacass_short.csv -profile singularity --skip-kraken2`
results in the following:
`Missing Kraken2 DB arg`
One would need to specify the `--kraken2db` argument, which is a bit counter-intuitive to the role of `--skip-kraken2`.

**Comment by apeltzer** [comment]
Agreed - something that should be fixed 😓

**Comment by apeltzer** [comment]
I think I found your issue. The parameter is:

`--skip_kraken2` and not `--skip-kraken2` :-) 

If this isn't fixing the issue let me know again and reopen accordingly!
