### ISSUE TITLE
QUAST module not used in MultiQC

### ISSUE THREAD

**Issue by apeltzer** [nf-core/bacass#35]
https://github.com/ewels/MultiQC/issues/1351

So apparently it doesn't work with `${sample_id}_report.tsv` - maybe I should try ``${sample_id}.report.tsv` instead and/or configure a custom name for the MultiQC config for the pipeline:

```bash
quast_config:
    fn: *_report.tsv
```

could do the trick maybe :-)

**Comment by tamuanand** [comment]
Hi @apeltzer 

i tried the file name trick too, it didn't work - I had it like what you show.

Let me know if it works for you.

**Comment by apeltzer** [comment]
Fixed in dabaa2cc129e473e4f443ccf7f53e04ca2a7d8c1
