### ISSUE TITLE
kraken2db not being mounted for singularity

### ISSUE THREAD

**Issue by santiagorevale** [nf-core/bacass#36]
Hi there,

I downloaded the latest pipeline `v1.1.1` and ran it offline with the following command:

```
nextflow run $PWD/nf-core-bacass-1.1.1/workflow/ \
  -profile singularity \
  --kraken2db /path/to/krakendb \
  --input $PWD/samples.csv \
  --assembly_type long \
  --skip_annotation \
  --skip_polish \
  --assembler canu \
  --canu_args 'stopOnLowCoverage=0 minInputCoverage=0'
```

The contents of the kraken2db folder are
``` 
library
taxonomy
hash.k2d
opts.k2d
seqid2taxid.map
taxo.k2d
```

The error I'm getting is 
```
kraken2: database ("/path/to/krakendb") does not contain necessary file taxo.k2d
```

Here are the `.command.run` and `.command.sh` files (I added `.txt` at the end to be able to attach them)
[command.run.txt](https://github.com/nf-core/bacass/files/5628539/command.run.txt)
[command.sh.txt](https://github.com/nf-core/bacass/files/5628540/command.sh.txt)

In my profile file, I have defined
```
singularity {
    enabled = true
    autoMounts = true
    cacheDir = "/path/to/images/singularity/nfcore/"
}
```

Thanks for looking into this. I'm just wondering whether I'm missing something.

Cheers,
Santiago

**Comment by apeltzer** [comment]
Hrmpf, this looks like a weird bug. unfortunately one that we didn't catch in the CI tests, as we don't test kraken on the CI. I need to merge in the latest template #34 anyways these days, so that might  be something to get in the next fix release too & re-add this to CI to get it tested with a tiny kraken2 database similar to the one used by ViralRecon. 

Thanks for reporting !

**Comment by santiagorevale** [comment]
No problem! Is there a way to bypass this in the meantime? Thanks!

**Comment by apeltzer** [comment]
`--skip_kraken2` to skip it entirely. I'm afraid not really without skipping kraken entirely for now. I'll try to do it asap but pre-christmas thats sometimes a bit hard 😓 

Could be that its enough to follow the viralrecon example is most straightforward:

```
/*
 * PREPROCESSING: Uncompress Kraken2 database
 */
if (!params.skip_kraken2 && params.kraken2_db && !params.skip_assembly) {
    file(params.kraken2_db, checkIfExists: true)
    if (params.kraken2_db.endsWith('.tar.gz')) {
        process UNTAR_KRAKEN2_DB {
            label 'error_retry'
            if (params.save_reference) {
                publishDir "${params.outdir}/genome", mode: params.publish_dir_mode
            }

            input:
            path db from params.kraken2_db

            output:
            path "$untar" into ch_kraken2_db

            script:
            untar = db.toString() - '.tar.gz'
            """
            tar -xvf $db
            """
        }
    } else {
        ch_kraken2_db = file(params.kraken2_db)
    }
}
```

and then do this in the kraken2 / kraken2-long process:

```
input:

        path db from ch_kraken2_db
```

and in the script section:

```
 kraken2 \\
            --db $db \\
```

Not sure we will support direct input of gzipped kraken2 dbs, but that could be helpful as they are now available from AWS S3 buckets by the authors, so could be a nice addition.

**Comment by apeltzer** [comment]
Fairly easy change - wanna give it a go and I review? 
That would then fix `dev` and give us the possibility to get things fixed on `dev` for you to test ;-)

**Comment by santiagorevale** [comment]
Let me have a go

**Comment by santiagorevale** [comment]
should I add the `--save_reference` option? or should we always skip it?

**Comment by apeltzer** [comment]
Not required I think in this case...
