### ISSUE TITLE
Documentation broken link

### ISSUE THREAD

**Issue by danwiththeplan** [nf-core/bacass#42]
The documentation is at [https://nf-co.re/bacass/usage](https://nf-co.re/bacass/usage), but the link on the Documentation section of the nextflow page [https://nf-co.re/bacass#documentation](https://nf-co.re/bacass#documentation) goes to [https://nf-core/bacass/docs](https://nf-core/bacass/docs) (which is a broken link)

**Comment by apeltzer** [comment]
Thanks for reporting! This can be fixed via a Pull Reqest - if you want to, you can do it yourself on the `dev` branch or I / someone else will do it later :-)

**Comment by d4straub** [comment]
Seems solved to me.
