### ISSUE TITLE
Assembly Polishing is not working in the V2.0

### ISSUE THREAD

**Issue by varunshamanna** [nf-core/bacass#63]
## Description of the bug

Assembly Polishing step is not being performed in the workflow by default nor with the param --polish_method

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run nf-core/bacass --input 'sample_sheet.csv' --outdir /data/nihr/nanopore_sequencing/9_08_21/hybrid_assembly_output/ -profile docker --assembly_type hybrid -resume --kraken2db "https://genome-idx.s3.amazonaws.com/kraken/k2_standard_8gb_20210517.tar.gz"`

## Nextflow Installation

- Version: -- 21.04.3 

## Container engine

- Engine: Docker

![Screenshot from 2021-08-30 16-47-10](https://user-images.githubusercontent.com/43167012/131331868-37bcd3ec-9060-472b-a653-232b69c427b7.png)

**Comment by d4straub** [comment]
My notes say that assembly polishing is already done by Unicycler, that is used for hybrid assembly. Do you have there an opposing example/guideline/source? I am open to changing that, but need some sort of reference that this is beneficial.

**Comment by varunshamanna** [comment]
I am kind of new to nanopore analysis. I think from your code it means that assembly polishing is not required when doing the hybrid assembly. Is that right? Correct me if I am wrong. If it is so please close the issue.

**Comment by d4straub** [comment]
Yes, I just checked: Unicycler assembly (used for hybrid assembly) includes indeed already polishing with Pilon. So no additional polishing step is needed.
I close that issue, open another one if you recognize other oddities!
