### ISSUE TITLE
nf-validation on sample sheet

### ISSUE THREAD

**Issue by Daniel-VM** [nf-core/bacass#87]
Sample sheet validation could be performed via nf-validation plugin.
In addition,  tsv/csv documentation and parsing will need adjustments.

- [x] Fix README:  tsv file extension on sample sheet will fail, change it to csv
~~- [ ] Update  test data-set (`nf-core/test-dataset::bacass` ). Two options: 
        - Switch from tab to comma separated content/structure on sample sheets for testing (I prefer this one) . 
        - Or Change file extensions on sample sheets from csv to tsv~~
- [x]  Add nf-validation on sample sheet

**Comment by Daniel-VM** [comment]
Validation fails on the sample sheet when attempting to read a tab-separated file with a *.csv extension.

This issue affects all test datasets within [nf-core/test-dataset::bacass](https://github.com/nf-core/test-datasets/tree/bacass). It might be advisable to consider changing the file extension from csv to tsv for the test dataset files.

**Comment by d4straub** [comment]
We could just add the same files with a tsv ending. I think its better to leave the old files in to keep older bacass versions running. Do you want to do it or should I?

**Comment by Daniel-VM** [comment]
Yes!. I agree.
